### ISSUE TITLE
Page is not mobile friendly

### ISSUE THREAD

**Issue by kalanavw** [vasuskimo/Skimo_Newton_Issues#50] opened 2020-04-29 17:22 UTC

**Comment by vasuskimo** [comment] 2020-04-29 18:30
If you are referring to the landing page, newton.html, then try again. If you are referring to the home page it is a duplicate of https://github.com/vasuskimo/Skimo_Newton_Issues/issues/44

**Closed as completed by vasuskimo** 2020-04-29 18:30 UTC
